// Sample accessions
export const EXAMPLE_ACCESSIONS = [
  "NP_001193600.1",
  "Q26473",
  "NP_000146.2",
  "NP_003286.1",
  "NP_000517.2",
];

//  Different raw sequences 
export const EXAMPLE_SEQUENCES = [
  "MKILVFMILVFMILVFMILVFALAVILWILVFMILVFMILVFMILVFMILVFMILVFMILVF",
  "MKRSTDDEQKRKSEDEKQKLSSNTTNQNHHQQKKEDEEDESSSTTTNNNQQQKKKEDDEQKR",
  "MILVFMILVFMILVFMILVFILVFMILVFMILVFMILVFMILVFMILVFMILVFMILVFMILVF",
  "MGILVFMILVFMILVFMILVFALAVILWILVFMILVFMILVFALMPFLWILVFMILVFMILVFMILVFMILVFMILVFMILVFMILVF",
  "MACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWY",
];

function pickRandom<T>(items: T[]): T {
  return items[Math.floor(Math.random() * items.length)];
}

export function getRandomExampleAccession(): string {
  return pickRandom(EXAMPLE_ACCESSIONS);
}

export function getRandomExampleSequence(): string {
  return pickRandom(EXAMPLE_SEQUENCES);
}
